# Generated by Django 4.0 on 2021-12-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default=888888888, max_length=20),
            preserve_default=False,
        ),
    ]
