# Generated by Django 4.0 on 2021-12-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_alter_livros_data_cadastro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emprestimo',
        ),
    ]
